codecov:
 notify:
  require_ci_to_pass: yes
 token: 58b39ec7-536f-492c-8686-6dd71bf93f86

coverage:
  status:
    project:
      tests:
        target: 60%  # Minimum coverage ratio that the commit must meet to be considered a success.
